
-- Tabela: EMPRESAS
CREATE TABLE empresas_workwell (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   nome VARCHAR(255) NOT NULL,
                                   cnpj VARCHAR(18) UNIQUE NOT NULL,
                                   setor VARCHAR(100) NOT NULL,
                                   data_cadastro DATE NOT NULL
);