
-- Tabela: DEPARTAMENTOS
CREATE TABLE departamentos_workwell (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        nome VARCHAR(100) NOT NULL,
                                        empresa_id BIGINT NOT NULL,
                                        data_cadastro DATE NOT NULL,
                                        CONSTRAINT fk_departamentos_empresa FOREIGN KEY (empresa_id) REFERENCES empresas_workwell(id)
);