-- Tabela: USUARIOS
CREATE TABLE usuarios_workwell (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   nome VARCHAR(255) NOT NULL,
                                   email VARCHAR(255) UNIQUE NOT NULL,
                                   senha VARCHAR(255) NOT NULL,
                                   role VARCHAR(20) DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')) NOT NULL,
                                   empresa_id BIGINT NOT NULL,
                                   departamento_id BIGINT,
                                   data_cadastro DATE NOT NULL,
                                   CONSTRAINT fk_usuarios_empresa FOREIGN KEY (empresa_id) REFERENCES empresas_workwell(id),
                                   CONSTRAINT fk_usuarios_departamento FOREIGN KEY (departamento_id) REFERENCES departamentos_workwell(id)
);