-- Tabela: METRICAS_SAUDE
CREATE TABLE metricas_saude_workwell (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         usuario_id BIGINT NOT NULL,
                                         data DATE NOT NULL,
                                         qualidade_sono SMALLINT CHECK (qualidade_sono BETWEEN 1 AND 10) NOT NULL,
                                         atividade_fisica INTEGER NOT NULL, -- minutos por dia
                                         isolamento_social SMALLINT CHECK (isolamento_social BETWEEN 1 AND 10) NOT NULL,
                                         consumo_agua INTEGER NOT NULL, -- copos por dia
                                         CONSTRAINT fk_metricas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios_workwell(id)
);