-- Tabela: ALERTAS_BURNOUT
CREATE TABLE alertas_burnout_workwell (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          usuario_id BIGINT NOT NULL,
                                          data DATE NOT NULL,
                                          nivel_risco VARCHAR(20) CHECK (nivel_risco IN ('BAIXO', 'MEDIO', 'ALTO', 'CRITICO')),
                                          pontuacao_total INTEGER NOT NULL,
                                          recomendacoes VARCHAR(1000) NOT NULL,
                                          CONSTRAINT fk_alertas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios_workwell(id)
);